#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleObjCContainerKeyValueCoding.m
src/_MulleObjCInstanceVariableAccess.m
src/_MulleObjCKVCInformation.m
src/NSArray+KeyValueCoding.m
src/NSArray+MulleObjCKVCArithmetic.m
src/NSDictionary+KeyValueCoding.m
src/NSMutableDictionary+KeyValueCoding.m
src/NSNumber+MulleObjCKVCArithmetic.m
src/NSObject+KVCSupport.m
src/NSObject+KeyValueCoding.m
src/NSObject+_MulleObjCKVCInformation.m
src/NSProxy+_MulleObjCKVCInformation.m
src/NSSet+KeyValueCoding.m
src/NSSortDescriptor+NSKeyValueCoding.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCKVCFoundation.m
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/MulleObjCKVCFoundation-standalone.m
)
