language: c

dist: trusty
sudo: required

before_install:
  - wget -q -O- https://raw.githubusercontent.com/mulle-objc/mulle-objc-developer/release/install-ubuntu.sh | sudo APTFLAGS=-y sh

script:
   - mulle-install -vv -V --prefix /tmp
   - mulle-test -v -V
