/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use CD7C4BB0-69E8-44C1-A63F-84473F919E0E instead of MulleObjCStandardFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCStandardFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCStandardFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCStandardFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCStandardFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCStandardFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCStandardFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCStandardFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCStandardFoundation/MulleObjCStandardFoundation.h>   // MulleObjCStandardFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCKVCFoundation-include.h")
#  include "_MulleObjCKVCFoundation-include.h"
# endif
#endif

