/*
*   This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_INCLUDE_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_kvc_foundation_include_h__
#define _mulle_objc_kvc_foundation_include_h__

/* no headers */

#endif
