#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
src/MulleObjCContainerKeyValueCoding.h
src/_MulleObjCInstanceVariableAccess.h
src/MulleObjCKVCFoundation.h
src/_MulleObjCKVCInformation.h
src/MulleObjCLoader+MulleObjCKVCFoundation.h
src/NSNumber+MulleObjCKVCArithmetic.h
src/NSObject+KVCSupport.h
src/NSObject+KeyValueCoding.h
src/NSObject+_MulleObjCKVCInformation.h
src/import.h
src/include.h
)

